import type { Metadata, Viewport } from "next";
import "./globals.css";
import "./experience.css";
import { appUrl as resolveAppUrl } from "@/lib/app-url";

const appUrl = resolveAppUrl();

export const metadata: Metadata = {
  metadataBase: new URL(appUrl),
  title: {
    default: "MYSTOREY — Votre boutique, votre histoire",
    template: "%s | MYSTOREY",
  },
  description:
    "Arrêtez de renvoyer les mêmes photos et les mêmes prix sur WhatsApp. Créez gratuitement votre boutique MYSTOREY : un seul lien, vos produits, vos prix, et des commandes claires.",
  applicationName: "MYSTOREY",
  creator: "MYSTOREY",
  publisher: "MYSTOREY",
  // Generated by scripts/generate-icons.mjs. The favicon used to be a 520x520 / 321 KB
  // PNG and the Apple icon a 1254x1254 / 894 KB one, both fetched on every page.
  icons: {
    icon: [
      { url: "/icon-32.png", type: "image/png", sizes: "32x32" },
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    shortcut: [{ url: "/icon-32.png", type: "image/png", sizes: "32x32" }],
    apple: [{ url: "/apple-icon.png", type: "image/png", sizes: "180x180" }],
  },
  manifest: "/manifest.webmanifest",
  keywords: [
    "boutique en ligne",
    "commerce bénin",
    "vendeuse",
    "boutique africaine",
    "WhatsApp commerce",
    "MYSTOREY",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "MYSTOREY — Votre boutique, votre histoire",
    description:
      "Un seul lien pour montrer tous vos produits et recevoir des commandes claires, depuis votre téléphone. Gratuit pour commencer.",
    url: appUrl,
    siteName: "MYSTOREY",
    locale: "fr_FR",
    type: "website",
    // A 1200x630 card, not the square logo: it is the shape WhatsApp, Facebook and X
    // crop to, and the declared dimensions were wrong for the file anyway.
    images: [{ url: "/og-card.png", width: 1200, height: 630, alt: "MYSTOREY — Votre boutique, votre histoire" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "MYSTOREY",
    description:
      "Un seul lien pour vos produits, vos prix et vos commandes. Gratuit pour commencer.",
    images: [{ url: "/og-card.png", alt: "MYSTOREY — Votre boutique, votre histoire" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#4f1d2d",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" data-scroll-behavior="smooth">
      <body>{children}</body>
    </html>
  );
}
