export type ProductRow = { id: string; name: string; note: string | null; price: number; image_url: string | null; description?: string | null; is_featured?: boolean; is_available?: boolean; category_id?: string | null; product_media?: { id: string; public_url: string; position: number }[] };
export type ProductView = { id: string; name: string; price: string; note: string; description: string; image: string | null; images: string[]; unitPrice: number; featured: boolean; available: boolean; categoryId: string | null };
const fcf = new Intl.NumberFormat("fr-FR");
export function formatPrice(value: number): string { return `${fcf.format(value)} FCFA`; }
export function toProductView(row: ProductRow): ProductView { const media = [...(row.product_media ?? [])].sort((a, b) => a.position - b.position).map((item) => item.public_url); const images = media.length ? media : (row.image_url ? [row.image_url] : []); return { id: row.id, name: row.name, price: formatPrice(row.price), note: row.note ?? "", description: row.description ?? "", image: images[0] ?? null, images, unitPrice: row.price, featured: Boolean(row.is_featured), available: row.is_available ?? true, categoryId: row.category_id ?? null }; }
export const demoProducts: ProductView[] = [
  { id: "1", name: "Escarpins Éclat", price: "28 000 FCFA", note: "Pièce signature", description: "", image: "/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.14.45.jpeg", images: ["/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.14.45.jpeg"], unitPrice: 28000, featured: true, available: true, categoryId: null },
  { id: "2", name: "Sandales Bijoux", price: "19 500 FCFA", note: "Disponible maintenant", description: "", image: "/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.14.46.jpeg", images: ["/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.14.46.jpeg"], unitPrice: 19500, featured: false, available: true, categoryId: null },
  { id: "3", name: "Sac Bordeaux", price: "35 000 FCFA", note: "Édition limitée", description: "", image: "/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.26.51.jpeg", images: ["/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.26.51.jpeg"], unitPrice: 35000, featured: false, available: true, categoryId: null },
  { id: "4", name: "Sac Ivoire", price: "16 000 FCFA", note: "Finition délicate", description: "", image: "/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.26.52.jpeg", images: ["/images/Image_products/WhatsApp%20Image%202026-09-02%20at%2016.26.52.jpeg"], unitPrice: 16000, featured: false, available: true, categoryId: null }
];